version: '3'

services:
  php: 
    build: .
    volumes:
      - .:/var/www/html:rw
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/var &&
              chmod -R 777 /var/www/html/var &&
              php-fpm"

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  database_test:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_test_data:/var/lib/postgresql/data:rw

  web: 
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "80:80" 

volumes:
  database_data:
  database_test_data:
