version: '3'

services:
  php: # Add this new service
    image: php:8.2-fpm-alpine
    volumes:
      - .:/var/www/html:rw
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/var &&
              chmod -R 777 /var/www/html/var &&
              php-fpm"
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###


  web: # Add this new service
    image: nginx:stable-alpine
    volumes:
      - .:/var/www/html:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    ports:
      - "80:80" # Expose the port 80 on the host machine and map it to the port 80 of the container

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###
