name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate


    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests (PHP Unit)
      run: ./vendor/bin/phpunit
